<?php

namespace Juanparati\ISOCodes\Databases\Countries;

use Juanparati\ISOCodes\Databases\ISODatabaseBase;


/**
 * List of country codes with their ISO 3166-1 alpha-2, alpha3, numeric code and TLD.
 *
 * @see https://www.iban.com/country-codes
 * @see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
 * @see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
 * @see https://en.wikipedia.org/wiki/Country_code_top-level_domain
 */
class CountryCodes extends ISODatabaseBase
{

    protected array $db = [
        'AF' => [
            'alpha2'     => 'AF',
            'alpha3'     => 'AFG',
            'numeric'    => '004',
            'tld'        => '.af',
            'currencies' => ['AFN',],
            'continents'  => ['AS'],
        ],
        'AX' => [
            'alpha2'     => 'AX',
            'alpha3'     => 'ALA',
            'numeric'    => '248',
            'tld'        => '.ax',
            'currencies' => ['EUR',],
            'languages'  => ['SV'],
            'continents'  => ['EU'],
        ],
        'AL' => [
            'alpha2'     => 'AL',
            'alpha3'     => 'ALB',
            'numeric'    => '008',
            'tld'        => '.al',
            'currencies' => ['ALL',],
            'languages'  => ['SQ'],
            'continents'  => ['EU'],
        ],
        'DZ' => [
            'alpha2'     => 'DZ',
            'alpha3'     => 'DZA',
            'numeric'    => '012',
            'tld'        => '.dz',
            'currencies' => ['DZD',],
            'continents'  => ['AF'],
        ],
        'AS' => [
            'alpha2'     => 'AS',
            'alpha3'     => 'ASM',
            'numeric'    => '016',
            'tld'        => '.as',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'AD' => [
            'alpha2'     => 'AD',
            'alpha3'     => 'AND',
            'numeric'    => '020',
            'tld'        => '.ad',
            'currencies' => ['EUR',],
            'languages'  => ['CA'],
            'continents'  => ['EU'],
        ],
        'AO' => [
            'alpha2'     => 'AO',
            'alpha3'     => 'AGO',
            'numeric'    => '024',
            'tld'        => '.ao',
            'currencies' => ['AOA',],
            'continents'  => ['AF'],
        ],
        'AI' => [
            'alpha2'     => 'AI',
            'alpha3'     => 'AIA',
            'numeric'    => '660',
            'tld'        => '.ai',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'AQ' => [
            'alpha2'     => 'AQ',
            'alpha3'     => 'ATA',
            'numeric'    => '010',
            'tld'        => '.aq',
            'currencies' => ['ARS', 'AUD', 'BGN', 'BRL', 'BYN', 'CLP', 'CNY', 'CZK', 'EUR', 'GBP', 'INR', 'JPY', 'KRW', 'NOK', 'NZD', 'PEN', 'PKR', 'PLN', 'RON', 'RUB', 'SEK', 'UAH', 'USD', 'UYU', 'ZAR',],
            'continents'  => ['AN'],
        ],
        'AG' => [
            'alpha2'     => 'AG',
            'alpha3'     => 'ATG',
            'numeric'    => '028',
            'tld'        => '.ag',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'AR' => [
            'alpha2'     => 'AR',
            'alpha3'     => 'ARG',
            'numeric'    => '032',
            'tld'        => '.ar',
            'currencies' => ['ARS',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'AM' => [
            'alpha2'     => 'AM',
            'alpha3'     => 'ARM',
            'numeric'    => '051',
            'tld'        => '.am',
            'currencies' => ['AMD',],
            'languages'  => ['HY'],
            'continents'  => ['AS'],
        ],
        'AW' => [
            'alpha2'     => 'AW',
            'alpha3'     => 'ABW',
            'numeric'    => '533',
            'tld'        => '.aw',
            'currencies' => ['AWG',],
            'continents'  => ['NA'],
        ],
        'AU' => [
            'alpha2'     => 'AU',
            'alpha3'     => 'AUS',
            'numeric'    => '036',
            'tld'        => '.au',
            'currencies' => ['AUD',],
            'continents'  => ['OC'],
        ],
        'AT' => [
            'alpha2'     => 'AT',
            'alpha3'     => 'AUT',
            'numeric'    => '040',
            'tld'        => '.at',
            'currencies' => ['EUR',],
            'languages'  => ['DE'],
            'continents'  => ['EU'],
        ],
        'AZ' => [
            'alpha2'     => 'AZ',
            'alpha3'     => 'AZE',
            'numeric'    => '031',
            'tld'        => '.az',
            'currencies' => ['AZN',],
            'continents'  => ['AS'],
        ],
        'BS' => [
            'alpha2'     => 'BS',
            'alpha3'     => 'BHS',
            'numeric'    => '044',
            'tld'        => '.bs',
            'currencies' => ['BSD',],
            'continents'  => ['NA'],
        ],
        'BH' => [
            'alpha2'     => 'BH',
            'alpha3'     => 'BHR',
            'numeric'    => '048',
            'tld'        => '.bh',
            'currencies' => ['BHD',],
            'continents'  => ['AS'],
        ],
        'BD' => [
            'alpha2'     => 'BD',
            'alpha3'     => 'BGD',
            'numeric'    => '050',
            'tld'        => '.bd',
            'currencies' => ['BDT',],
            'continents'  => ['AS'],
        ],
        'BB' => [
            'alpha2'     => 'BB',
            'alpha3'     => 'BRB',
            'numeric'    => '052',
            'tld'        => '.bb',
            'currencies' => ['BBD',],
            'continents'  => ['NA'],
        ],
        'BY' => [
            'alpha2'     => 'BY',
            'alpha3'     => 'BLR',
            'numeric'    => '112',
            'tld'        => '.by',
            'currencies' => ['BYN',],
            'languages'  => ['BE', 'RU'],
            'continents'  => ['EU'],
        ],
        'BE' => [
            'alpha2'     => 'BE',
            'alpha3'     => 'BEL',
            'numeric'    => '056',
            'tld'        => '.be',
            'currencies' => ['EUR',],
            'languages'  => ['NL', 'FR', 'DE'],
            'continents'  => ['EU'],
        ],
        'BZ' => [
            'alpha2'     => 'BZ',
            'alpha3'     => 'BLZ',
            'numeric'    => '084',
            'tld'        => '.bz',
            'currencies' => ['BZD',],
            'continents'  => ['NA'],
        ],
        'BJ' => [
            'alpha2'     => 'BJ',
            'alpha3'     => 'BEN',
            'numeric'    => '204',
            'tld'        => '.bj',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'BM' => [
            'alpha2'     => 'BM',
            'alpha3'     => 'BMU',
            'numeric'    => '060',
            'tld'        => '.bm',
            'currencies' => ['BMD',],
            'continents'  => ['NA'],
        ],
        'BT' => [
            'alpha2'     => 'BT',
            'alpha3'     => 'BTN',
            'numeric'    => '064',
            'tld'        => '.bt',
            'currencies' => ['BTN',],
            'continents'  => ['AS'],
        ],
        'BO' => [
            'alpha2'     => 'BO',
            'alpha3'     => 'BOL',
            'numeric'    => '068',
            'tld'        => '.bo',
            'currencies' => ['BOB',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'BQ' => [
            'alpha2'     => 'BQ',
            'alpha3'     => 'BES',
            'numeric'    => '535',
            'tld'        => '.bq',
            'currencies' => ['USD',],
            'continents'  => ['SA'],
        ],
        'BA' => [
            'alpha2'     => 'BA',
            'alpha3'     => 'BIH',
            'numeric'    => '070',
            'tld'        => '.ba',
            'currencies' => ['BAM',],
            'languages'  => ['BS', 'HR', 'SR'],
            'continents'  => ['EU'],
        ],
        'BW' => [
            'alpha2'     => 'BW',
            'alpha3'     => 'BWA',
            'numeric'    => '072',
            'tld'        => '.bw',
            'currencies' => ['BWP',],
            'continents'  => ['AF'],
        ],
        'BV' => [
            'alpha2'     => 'BV',
            'alpha3'     => 'BVT',
            'numeric'    => '074',
            'tld'        => '.bv',
            'currencies' => ['NOK',],
            'continents'  => ['AN'],
        ],
        'BR' => [
            'alpha2'     => 'BR',
            'alpha3'     => 'BRA',
            'numeric'    => '076',
            'tld'        => '.br',
            'currencies' => ['BRL',],
            'languages'  => ['PT'],
            'continents'  => ['SA'],
        ],
        'IO' => [
            'alpha2'     => 'IO',
            'alpha3'     => 'IOT',
            'numeric'    => '086',
            'tld'        => '.io',
            'currencies' => ['GBP',],
            'continents'  => ['OC'],
        ],
        'BN' => [
            'alpha2'     => 'BN',
            'alpha3'     => 'BRN',
            'numeric'    => '096',
            'tld'        => '.bn',
            'currencies' => ['BND', 'SGD',],
            'continents'  => ['AS'],
        ],
        'BG' => [
            'alpha2'     => 'BG',
            'alpha3'     => 'BGR',
            'numeric'    => '100',
            'tld'        => '.bg',
            'currencies' => ['BGN',],
            'languages'  => ['BG'],
            'continents'  => ['EU'],
        ],
        'BF' => [
            'alpha2'     => 'BF',
            'alpha3'     => 'BFA',
            'numeric'    => '854',
            'tld'        => '.bf',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'BI' => [
            'alpha2'     => 'BI',
            'alpha3'     => 'BDI',
            'numeric'    => '108',
            'tld'        => '.bi',
            'currencies' => ['BIF',],
            'continents'  => ['AF'],
        ],
        'CV' => [
            'alpha2'     => 'CV',
            'alpha3'     => 'CPV',
            'numeric'    => '132',
            'tld'        => '.cv',
            'currencies' => ['CVE',],
            'continents'  => ['AF'],
        ],
        'KH' => [
            'alpha2'     => 'KH',
            'alpha3'     => 'KHM',
            'numeric'    => '116',
            'tld'        => '.kh',
            'currencies' => ['KHR',],
            'continents'  => ['AS'],
        ],
        'CM' => [
            'alpha2'     => 'CM',
            'alpha3'     => 'CMR',
            'numeric'    => '120',
            'tld'        => '.cm',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'CA' => [
            'alpha2'     => 'CA',
            'alpha3'     => 'CAN',
            'numeric'    => '124',
            'tld'        => '.ca',
            'currencies' => ['CAD',],
            'languages'  => ['EN', 'FR'],
            'continents'  => ['NA'],
        ],
        'KY' => [
            'alpha2'     => 'KY',
            'alpha3'     => 'CYM',
            'numeric'    => '136',
            'tld'        => '.ky',
            'currencies' => ['KYD',],
            'continents'  => ['NA'],
        ],
        'CF' => [
            'alpha2'     => 'CF',
            'alpha3'     => 'CAF',
            'numeric'    => '140',
            'tld'        => '.cf',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'TD' => [
            'alpha2'     => 'TD',
            'alpha3'     => 'TCD',
            'numeric'    => '148',
            'tld'        => '.td',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'CL' => [
            'alpha2'     => 'CL',
            'alpha3'     => 'CHL',
            'numeric'    => '152',
            'tld'        => '.cl',
            'currencies' => ['CLP',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'CN' => [
            'alpha2'     => 'CN',
            'alpha3'     => 'CHN',
            'numeric'    => '156',
            'tld'        => '.cn',
            'currencies' => ['CNY',],
            'continents'  => ['AS'],
        ],
        'CX' => [
            'alpha2'     => 'CX',
            'alpha3'     => 'CXR',
            'numeric'    => '162',
            'tld'        => '.cx',
            'currencies' => ['AUD',],
            'continents'  => ['AS'],
        ],
        'CC' => [
            'alpha2'     => 'CC',
            'alpha3'     => 'CCK',
            'numeric'    => '166',
            'tld'        => '.cc',
            'currencies' => ['AUD',],
            'continents'  => ['AS'],
        ],
        'CO' => [
            'alpha2'     => 'CO',
            'alpha3'     => 'COL',
            'numeric'    => '170',
            'tld'        => '.co',
            'currencies' => ['COP',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'KM' => [
            'alpha2'     => 'KM',
            'alpha3'     => 'COM',
            'numeric'    => '174',
            'tld'        => '.km',
            'currencies' => ['KMF',],
            'continents'  => ['AF'],
        ],
        'CG' => [
            'alpha2'     => 'CG',
            'alpha3'     => 'COG',
            'numeric'    => '178',
            'tld'        => '.cg',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'CD' => [
            'alpha2'     => 'CD',
            'alpha3'     => 'COD',
            'numeric'    => '180',
            'tld'        => '.cd',
            'currencies' => ['CDF',],
            'continents'  => ['AF'],
        ],
        'CK' => [
            'alpha2'     => 'CK',
            'alpha3'     => 'COK',
            'numeric'    => '184',
            'tld'        => '.ck',
            'currencies' => ['NZD',],
            'continents'  => ['OC'],
        ],
        'CR' => [
            'alpha2'     => 'CR',
            'alpha3'     => 'CRI',
            'numeric'    => '188',
            'tld'        => '.cr',
            'currencies' => ['CRC',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'CI' => [
            'alpha2'     => 'CI',
            'alpha3'     => 'CIV',
            'numeric'    => '384',
            'tld'        => '.ci',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'HR' => [
            'alpha2'     => 'HR',
            'alpha3'     => 'HRV',
            'numeric'    => '191',
            'tld'        => '.hr',
            'currencies' => ['HRK',],
            'languages'  => ['HR', 'SR', 'HU', 'CS', 'SK'],
            'continents'  => ['EU'],
        ],
        'CU' => [
            'alpha2'     => 'CU',
            'alpha3'     => 'CUB',
            'numeric'    => '192',
            'tld'        => '.cu',
            'currencies' => ['CUC', 'CUP',],
            'continents'  => ['NA'],
        ],
        'CW' => [
            'alpha2'     => 'CW',
            'alpha3'     => 'CUW',
            'numeric'    => '531',
            'tld'        => '.cw',
            'currencies' => ['ANG',],
            'continents'  => ['NA'],
        ],
        'CY' => [
            'alpha2'     => 'CY',
            'alpha3'     => 'CYP',
            'numeric'    => '196',
            'tld'        => '.cy',
            'currencies' => ['EUR',],
            'continents'  => ['AS', 'EU'],
        ],
        'CZ' => [
            'alpha2'     => 'CZ',
            'alpha3'     => 'CZE',
            'numeric'    => '203',
            'tld'        => '.cz',
            'currencies' => ['CZK',],
            'languages'  => ['CS', 'SK'],
            'continents'  => ['EU'],
        ],
        'DK' => [
            'alpha2'     => 'DK',
            'alpha3'     => 'DNK',
            'numeric'    => '208',
            'tld'        => '.dk',
            'currencies' => ['DKK',],
            'languages'  => ['DA'],
            'continents'  => ['EU'],
        ],
        'DJ' => [
            'alpha2'     => 'DJ',
            'alpha3'     => 'DJI',
            'numeric'    => '262',
            'tld'        => '.dj',
            'currencies' => ['DJF',],
            'continents'  => ['AF'],
        ],
        'DM' => [
            'alpha2'     => 'DM',
            'alpha3'     => 'DMA',
            'numeric'    => '212',
            'tld'        => '.dm',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'DO' => [
            'alpha2'     => 'DO',
            'alpha3'     => 'DOM',
            'numeric'    => '214',
            'tld'        => '.do',
            'currencies' => ['DOP',],
            'continents'  => ['NA'],
        ],
        'EC' => [
            'alpha2'     => 'EC',
            'alpha3'     => 'ECU',
            'numeric'    => '218',
            'tld'        => '.ec',
            'currencies' => ['USD',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'EG' => [
            'alpha2'     => 'EG',
            'alpha3'     => 'EGY',
            'numeric'    => '818',
            'tld'        => '.eg',
            'currencies' => ['EGP',],
            'continents'  => ['AS'],
        ],
        'SV' => [
            'alpha2'     => 'SV',
            'alpha3'     => 'SLV',
            'numeric'    => '222',
            'tld'        => '.sv',
            'currencies' => ['USD',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'GQ' => [
            'alpha2'     => 'GQ',
            'alpha3'     => 'GNQ',
            'numeric'    => '226',
            'tld'        => '.gq',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'ER' => [
            'alpha2'     => 'ER',
            'alpha3'     => 'ERI',
            'numeric'    => '232',
            'tld'        => '.er',
            'currencies' => ['ERN',],
            'continents'  => ['AF'],
        ],
        'EE' => [
            'alpha2'     => 'EE',
            'alpha3'     => 'EST',
            'numeric'    => '233',
            'tld'        => '.ee',
            'currencies' => ['EUR',],
            'languages'  => ['ET'],
            'continents'  => ['EU'],
        ],
        'ET' => [
            'alpha2'     => 'ET',
            'alpha3'     => 'ETH',
            'numeric'    => '231',
            'tld'        => '.et',
            'currencies' => ['ETB',],
            'continents'  => ['AF'],
        ],
        'SZ' => [
            'alpha2'     => 'SZ',
            'alpha3'     => 'SWZ',
            'numeric'    => '748',
            'tld'        => '.sz',
            'currencies' => ['SZL', 'ZAR',],
            'continents'  => ['AF'],
        ],
        'FK' => [
            'alpha2'     => 'FK',
            'alpha3'     => 'FLK',
            'numeric'    => '238',
            'tld'        => '.fk',
            'currencies' => ['FKP',],
            'continents'  => ['SA'],
        ],
        'FO' => [
            'alpha2'     => 'FO',
            'alpha3'     => 'FRO',
            'numeric'    => '234',
            'tld'        => '.fo',
            'currencies' => ['DKK',],
            'languages'  => ['DA', 'FO'],
            'continents'  => ['EU'],
        ],
        'FJ' => [
            'alpha2'     => 'FJ',
            'alpha3'     => 'FJI',
            'numeric'    => '242',
            'tld'        => '.fj',
            'currencies' => ['FJD',],
            'continents'  => ['OC'],
        ],
        'FI' => [
            'alpha2'     => 'FI',
            'alpha3'     => 'FIN',
            'numeric'    => '246',
            'tld'        => '.fi',
            'currencies' => ['EUR',],
            'languages'  => ['FI', 'SV'],
            'continents'  => ['EU'],
        ],
        'FR' => [
            'alpha2'     => 'FR',
            'alpha3'     => 'FRA',
            'numeric'    => '250',
            'tld'        => '.fr',
            'currencies' => ['EUR',],
            'languages'  => ['FR', 'CO'],
            'continents'  => ['EU'],
        ],
        'GF' => [
            'alpha2'     => 'GF',
            'alpha3'     => 'GUF',
            'numeric'    => '254',
            'tld'        => '.gf',
            'currencies' => ['EUR',],
            'continents'  => ['SA'],
        ],
        'PF' => [
            'alpha2'     => 'PF',
            'alpha3'     => 'PYF',
            'numeric'    => '258',
            'tld'        => '.pf',
            'currencies' => ['XPF',],
            'continents'  => ['OC'],
        ],
        'TF' => [
            'alpha2'     => 'TF',
            'alpha3'     => 'ATF',
            'numeric'    => '260',
            'tld'        => '.tf',
            'currencies' => ['EUR',],
            'continents'  => ['AN'],
        ],
        'GA' => [
            'alpha2'     => 'GA',
            'alpha3'     => 'GAB',
            'numeric'    => '266',
            'tld'        => '.ga',
            'currencies' => ['XAF',],
            'continents'  => ['AF'],
        ],
        'GM' => [
            'alpha2'     => 'GM',
            'alpha3'     => 'GMB',
            'numeric'    => '270',
            'tld'        => '.gm',
            'currencies' => ['GMD',],
            'continents'  => ['AF'],
        ],
        'GE' => [
            'alpha2'     => 'GE',
            'alpha3'     => 'GEO',
            'numeric'    => '268',
            'tld'        => '.ge',
            'currencies' => ['GEL',],
            'continents'  => ['AS'],
        ],
        'DE' => [
            'alpha2'     => 'DE',
            'alpha3'     => 'DEU',
            'numeric'    => '276',
            'tld'        => '.de',
            'currencies' => ['EUR',],
            'languages'  => ['DE', 'HR', 'HU', 'SL'],
            'continents'  => ['EU'],
        ],
        'GH' => [
            'alpha2'     => 'GH',
            'alpha3'     => 'GHA',
            'numeric'    => '288',
            'tld'        => '.gh',
            'currencies' => ['GHS',],
            'continents'  => ['AF'],
        ],
        'GI' => [
            'alpha2'     => 'GI',
            'alpha3'     => 'GIB',
            'numeric'    => '292',
            'tld'        => '.gi',
            'currencies' => ['GIP', 'GBP'],
            'continents'  => ['EU'],
        ],
        'GR' => [
            'alpha2'     => 'GR',
            'alpha3'     => 'GRC',
            'numeric'    => '300',
            'tld'        => '.gr',
            'currencies' => ['EUR',],
            'languages'  => ['EL'],
            'continents'  => ['EU'],
        ],
        'GL' => [
            'alpha2'     => 'GL',
            'alpha3'     => 'GRL',
            'numeric'    => '304',
            'tld'        => '.gl',
            'currencies' => ['DKK',],
            'languages'  => ['DA', 'KL'],
            'continents'  => ['NA'],
        ],
        'GD' => [
            'alpha2'     => 'GD',
            'alpha3'     => 'GRD',
            'numeric'    => '308',
            'tld'        => '.gd',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'GP' => [
            'alpha2'     => 'GP',
            'alpha3'     => 'GLP',
            'numeric'    => '312',
            'tld'        => '.gp',
            'currencies' => ['EUR',],
            'continents'  => ['NA'],
        ],
        'GU' => [
            'alpha2'     => 'GU',
            'alpha3'     => 'GUM',
            'numeric'    => '316',
            'tld'        => '.gu',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'GT' => [
            'alpha2'     => 'GT',
            'alpha3'     => 'GTM',
            'numeric'    => '320',
            'tld'        => '.gt',
            'currencies' => ['GTQ',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'GG' => [
            'alpha2'     => 'GG',
            'alpha3'     => 'GGY',
            'numeric'    => '831',
            'tld'        => '.gg',
            'currencies' => ['GBP',],
            'continents'  => ['EU'],
        ],
        'GN' => [
            'alpha2'     => 'GN',
            'alpha3'     => 'GIN',
            'numeric'    => '324',
            'tld'        => '.gn',
            'currencies' => ['GNF',],
            'continents'  => ['AF'],
        ],
        'GW' => [
            'alpha2'     => 'GW',
            'alpha3'     => 'GNB',
            'numeric'    => '624',
            'tld'        => '.gw',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'GY' => [
            'alpha2'     => 'GY',
            'alpha3'     => 'GUY',
            'numeric'    => '328',
            'tld'        => '.gy',
            'currencies' => ['GYD',],
            'continents'  => ['SA'],
        ],
        'HT' => [
            'alpha2'     => 'HT',
            'alpha3'     => 'HTI',
            'numeric'    => '332',
            'tld'        => '.ht',
            'currencies' => ['HTG',],
            'continents'  => ['NA'],
        ],
        'HM' => [
            'alpha2'     => 'HM',
            'alpha3'     => 'HMD',
            'numeric'    => '334',
            'tld'        => '.hm',
            'currencies' => ['AUD',],
            'continents'  => ['AN'],
        ],
        'VA' => [
            'alpha2'     => 'VA',
            'alpha3'     => 'VAT',
            'numeric'    => '336',
            'tld'        => '.va',
            'currencies' => ['EUR',],
            'continents'  => ['EU'],
        ],
        'HN' => [
            'alpha2'     => 'HN',
            'alpha3'     => 'HND',
            'numeric'    => '340',
            'tld'        => '.hn',
            'currencies' => ['HNL',],
            'languages'  => ['ES', 'EN'],
            'continents'  => ['NA'],
        ],
        'HK' => [
            'alpha2'     => 'HK',
            'alpha3'     => 'HKG',
            'numeric'    => '344',
            'tld'        => '.hk',
            'currencies' => ['HKD',],
            'continents'  => ['AS'],
        ],
        'HU' => [
            'alpha2'     => 'HU',
            'alpha3'     => 'HUN',
            'numeric'    => '348',
            'tld'        => '.hu',
            'currencies' => ['HUF',],
            'languages'  => ['HU'],
            'continents'  => ['EU'],
        ],
        'IS' => [
            'alpha2'     => 'IS',
            'alpha3'     => 'ISL',
            'numeric'    => '352',
            'tld'        => '.is',
            'currencies' => ['ISK',],
            'languages'  => ['IS'],
            'continents'  => ['EU'],
        ],
        'IN' => [
            'alpha2'     => 'IN',
            'alpha3'     => 'IND',
            'numeric'    => '356',
            'tld'        => '.in',
            'currencies' => ['INR',],
            'continents'  => ['AS'],
        ],
        'ID' => [
            'alpha2'     => 'ID',
            'alpha3'     => 'IDN',
            'numeric'    => '360',
            'tld'        => '.id',
            'currencies' => ['IDR',],
            'continents'  => ['AS'],
        ],
        'IR' => [
            'alpha2'     => 'IR',
            'alpha3'     => 'IRN',
            'numeric'    => '364',
            'tld'        => '.ir',
            'currencies' => ['IRR',],
            'continents'  => ['AS'],
        ],
        'IQ' => [
            'alpha2'     => 'IQ',
            'alpha3'     => 'IRQ',
            'numeric'    => '368',
            'tld'        => '.iq',
            'currencies' => ['IQD',],
            'continents'  => ['AS'],
        ],
        'IE' => [
            'alpha2'     => 'IE',
            'alpha3'     => 'IRL',
            'numeric'    => '372',
            'tld'        => '.ie',
            'currencies' => ['EUR',],
            'languages'  => ['GA', 'EN'],
            'continents'  => ['EU'],
        ],
        'IM' => [
            'alpha2'     => 'IM',
            'alpha3'     => 'IMN',
            'numeric'    => '833',
            'tld'        => '.im',
            'currencies' => ['GBP',],
            'continents'  => ['EU'],
        ],
        'IL' => [
            'alpha2'     => 'IL',
            'alpha3'     => 'ISR',
            'numeric'    => '376',
            'tld'        => '.il',
            'currencies' => ['ILS',],
            'continents'  => ['AS'],
        ],
        'IT' => [
            'alpha2'     => 'IT',
            'alpha3'     => 'ITA',
            'numeric'    => '380',
            'tld'        => '.it',
            'currencies' => ['EUR',],
            'languages'  => ['IT', 'FR', 'DE', 'SL', 'SQ', 'SC', 'CO'],
            'continents'  => ['EU'],
        ],
        'JM' => [
            'alpha2'     => 'JM',
            'alpha3'     => 'JAM',
            'numeric'    => '388',
            'tld'        => '.jm',
            'currencies' => ['JMD',],
            'continents'  => ['NA'],
        ],
        'JP' => [
            'alpha2'     => 'JP',
            'alpha3'     => 'JPN',
            'numeric'    => '392',
            'tld'        => '.jp',
            'currencies' => ['JPY',],
            'continents'  => ['AS'],
        ],
        'JE' => [
            'alpha2'     => 'JE',
            'alpha3'     => 'JEY',
            'numeric'    => '832',
            'tld'        => '.je',
            'currencies' => ['GBP',],
            'continents'  => ['EU'],
        ],
        'JO' => [
            'alpha2'     => 'JO',
            'alpha3'     => 'JOR',
            'numeric'    => '400',
            'tld'        => '.jo',
            'currencies' => ['JOD',],
            'continents'  => ['AS'],
        ],
        'KZ' => [
            'alpha2'     => 'KZ',
            'alpha3'     => 'KAZ',
            'numeric'    => '398',
            'tld'        => '.kz',
            'currencies' => ['KZT',],
            'continents'  => ['AS'],
        ],
        'KE' => [
            'alpha2'     => 'KE',
            'alpha3'     => 'KEN',
            'numeric'    => '404',
            'tld'        => '.ke',
            'currencies' => ['KES',],
            'continents'  => ['AF'],
        ],
        'KI' => [
            'alpha2'     => 'KI',
            'alpha3'     => 'KIR',
            'numeric'    => '296',
            'tld'        => '.ki',
            'currencies' => ['AUD',],
            'continents'  => ['OC'],
        ],
        'KP' => [
            'alpha2'     => 'KP',
            'alpha3'     => 'PRK',
            'numeric'    => '408',
            'tld'        => '.kp',
            'currencies' => ['KPW',],
            'continents'  => ['AS'],
        ],
        'KR' => [
            'alpha2'     => 'KR',
            'alpha3'     => 'KOR',
            'numeric'    => '410',
            'tld'        => '.kr',
            'currencies' => ['KRW',],
            'continents'  => ['AS'],
        ],
        'KW' => [
            'alpha2'     => 'KW',
            'alpha3'     => 'KWT',
            'numeric'    => '414',
            'tld'        => '.kw',
            'currencies' => ['KWD',],
            'continents'  => ['AS'],
        ],
        'KG' => [
            'alpha2'     => 'KG',
            'alpha3'     => 'KGZ',
            'numeric'    => '417',
            'tld'        => '.kg',
            'currencies' => ['KGS',],
            'continents'  => ['AS'],
        ],
        'LA' => [
            'alpha2'     => 'LA',
            'alpha3'     => 'LAO',
            'numeric'    => '418',
            'tld'        => '.la',
            'currencies' => ['LAK',],
            'continents'  => ['AS'],
        ],
        'LV' => [
            'alpha2'     => 'LV',
            'alpha3'     => 'LVA',
            'numeric'    => '428',
            'tld'        => '.lv',
            'currencies' => ['EUR',],
            'languages'  => ['LV'],
            'continents'  => ['EU'],
        ],
        'LB' => [
            'alpha2'     => 'LB',
            'alpha3'     => 'LBN',
            'numeric'    => '422',
            'tld'        => '.lb',
            'currencies' => ['LBP',],
            'continents'  => ['AS'],
        ],
        'LS' => [
            'alpha2'     => 'LS',
            'alpha3'     => 'LSO',
            'numeric'    => '426',
            'tld'        => '.ls',
            'currencies' => ['LSL', 'ZAR',],
            'continents'  => ['AF'],
        ],
        'LR' => [
            'alpha2'     => 'LR',
            'alpha3'     => 'LBR',
            'numeric'    => '430',
            'tld'        => '.lr',
            'currencies' => ['LRD',],
            'continents'  => ['AF'],
        ],
        'LY' => [
            'alpha2'     => 'LY',
            'alpha3'     => 'LBY',
            'numeric'    => '434',
            'tld'        => '.ly',
            'currencies' => ['LYD',],
            'continents'  => ['AS'],
        ],
        'LI' => [
            'alpha2'     => 'LI',
            'alpha3'     => 'LIE',
            'numeric'    => '438',
            'tld'        => '.li',
            'currencies' => ['CHF',],
            'languages'  => ['DE'],
            'continents'  => ['EU'],
        ],
        'LT' => [
            'alpha2'     => 'LT',
            'alpha3'     => 'LTU',
            'numeric'    => '440',
            'tld'        => '.lt',
            'currencies' => ['EUR',],
            'languages'  => ['LT'],
            'continents'  => ['EU'],
        ],
        'LU' => [
            'alpha2'     => 'LU',
            'alpha3'     => 'LUX',
            'numeric'    => '442',
            'tld'        => '.lu',
            'currencies' => ['EUR',],
            'languages'  => ['FR', 'DE', 'LB'],
            'continents'  => ['EU'],
        ],
        'MO' => [
            'alpha2'     => 'MO',
            'alpha3'     => 'MAC',
            'numeric'    => '446',
            'tld'        => '.mo',
            'currencies' => ['MOP',],
            'continents'  => ['AS'],
        ],
        'MK' => [
            'alpha2'     => 'MK',
            'alpha3'     => 'MKD',
            'numeric'    => '807',
            'tld'        => '.mk',
            'currencies' => ['MKD',],
            'languages'  => ['MK', 'SQ'],
            'continents'  => ['EU'],
        ],
        'MG' => [
            'alpha2'     => 'MG',
            'alpha3'     => 'MDG',
            'numeric'    => '450',
            'tld'        => '.mg',
            'currencies' => ['MGA',],
            'continents'  => ['AF'],
        ],
        'MW' => [
            'alpha2'     => 'MW',
            'alpha3'     => 'MWI',
            'numeric'    => '454',
            'tld'        => '.mw',
            'currencies' => ['MWK',],
            'continents'  => ['AF'],
        ],
        'MY' => [
            'alpha2'     => 'MY',
            'alpha3'     => 'MYS',
            'numeric'    => '458',
            'tld'        => '.my',
            'currencies' => ['MYR',],
            'continents'  => ['AS'],
        ],
        'MV' => [
            'alpha2'     => 'MV',
            'alpha3'     => 'MDV',
            'numeric'    => '462',
            'tld'        => '.mv',
            'currencies' => ['MVR',],
            'continents'  => ['AS'],
        ],
        'ML' => [
            'alpha2'     => 'ML',
            'alpha3'     => 'MLI',
            'numeric'    => '466',
            'tld'        => '.ml',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'MT' => [
            'alpha2'     => 'MT',
            'alpha3'     => 'MLT',
            'numeric'    => '470',
            'tld'        => '.mt',
            'currencies' => ['EUR',],
            'languages'  => ['MT', 'EN'],
            'continents'  => ['EU'],
        ],
        'MH' => [
            'alpha2'     => 'MH',
            'alpha3'     => 'MHL',
            'numeric'    => '584',
            'tld'        => '.mh',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'MQ' => [
            'alpha2'     => 'MQ',
            'alpha3'     => 'MTQ',
            'numeric'    => '474',
            'tld'        => '.mq',
            'currencies' => ['EUR',],
            'continents'  => ['NA'],
        ],
        'MR' => [
            'alpha2'     => 'MR',
            'alpha3'     => 'MRT',
            'numeric'    => '478',
            'tld'        => '.mr',
            'currencies' => ['MRU',],
            'continents'  => ['AF'],
        ],
        'MU' => [
            'alpha2'     => 'MU',
            'alpha3'     => 'MUS',
            'numeric'    => '480',
            'tld'        => '.mu',
            'currencies' => ['MUR',],
            'continents'  => ['AF'],
        ],
        'YT' => [
            'alpha2'     => 'YT',
            'alpha3'     => 'MYT',
            'numeric'    => '175',
            'tld'        => '.yt',
            'currencies' => ['EUR',],
            'continents'  => ['AF'],
        ],
        'MX' => [
            'alpha2'     => 'MX',
            'alpha3'     => 'MEX',
            'numeric'    => '484',
            'tld'        => '.mx',
            'currencies' => ['MXN',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'FM' => [
            'alpha2'     => 'FM',
            'alpha3'     => 'FSM',
            'numeric'    => '583',
            'tld'        => '.fm',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'MD' => [
            'alpha2'     => 'MD',
            'alpha3'     => 'MDA',
            'numeric'    => '498',
            'tld'        => '.md',
            'currencies' => ['MDL',],
            'languages'  => ['RO', 'RU', 'UK'],
            'continents'  => ['EU'],
        ],
        'MC' => [
            'alpha2'     => 'MC',
            'alpha3'     => 'MCO',
            'numeric'    => '492',
            'tld'        => '.mc',
            'currencies' => ['EUR',],
            'languages'  => ['FR'],
            'continents'  => ['EU'],
        ],
        'MN' => [
            'alpha2'     => 'MN',
            'alpha3'     => 'MNG',
            'numeric'    => '496',
            'tld'        => '.mn',
            'currencies' => ['MNT',],
            'continents'  => ['AS'],
        ],
        'ME' => [
            'alpha2'     => 'ME',
            'alpha3'     => 'MNE',
            'numeric'    => '499',
            'tld'        => '.me',
            'currencies' => ['EUR',],
            'languages'  => ['SQ', 'BS', 'HR', 'SR'],
            'continents'  => ['EU'],
        ],
        'MS' => [
            'alpha2'     => 'MS',
            'alpha3'     => 'MSR',
            'numeric'    => '500',
            'tld'        => '.ms',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'MA' => [
            'alpha2'     => 'MA',
            'alpha3'     => 'MAR',
            'numeric'    => '504',
            'tld'        => '.ma',
            'currencies' => ['MAD',],
            'continents'  => ['AF'],
        ],
        'MZ' => [
            'alpha2'     => 'MZ',
            'alpha3'     => 'MOZ',
            'numeric'    => '508',
            'tld'        => '.mz',
            'currencies' => ['MZN',],
            'continents'  => ['AF'],
        ],
        'MM' => [
            'alpha2'     => 'MM',
            'alpha3'     => 'MMR',
            'numeric'    => '104',
            'tld'        => '.mm',
            'currencies' => ['MMK',],
            'continents'  => ['AS'],
        ],
        'NA' => [
            'alpha2'     => 'NA',
            'alpha3'     => 'NAM',
            'numeric'    => '516',
            'tld'        => '.na',
            'currencies' => ['NAD', 'ZAR',],
            'continents'  => ['AF'],
        ],
        'NR' => [
            'alpha2'     => 'NR',
            'alpha3'     => 'NRU',
            'numeric'    => '520',
            'tld'        => '.nr',
            'currencies' => ['AUD',],
            'continents'  => ['OC'],
        ],
        'NP' => [
            'alpha2'     => 'NP',
            'alpha3'     => 'NPL',
            'numeric'    => '524',
            'tld'        => '.np',
            'currencies' => ['NPR',],
            'continents'  => ['AS'],
        ],
        'NL' => [
            'alpha2'     => 'NL',
            'alpha3'     => 'NLD',
            'numeric'    => '528',
            'tld'        => '.nl',
            'currencies' => ['EUR',],
            'languages'  => ['NL'],
            'continents'  => ['EU'],
        ],
        'NC' => [
            'alpha2'     => 'NC',
            'alpha3'     => 'NCL',
            'numeric'    => '540',
            'tld'        => '.nc',
            'currencies' => ['XPF',],
            'continents'  => ['OC'],
        ],
        'NZ' => [
            'alpha2'     => 'NZ',
            'alpha3'     => 'NZL',
            'numeric'    => '554',
            'tld'        => '.nz',
            'currencies' => ['NZD',],
            'continents'  => ['OC'],
        ],
        'NI' => [
            'alpha2'     => 'NI',
            'alpha3'     => 'NIC',
            'numeric'    => '558',
            'tld'        => '.ni',
            'currencies' => ['NIO',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'NE' => [
            'alpha2'     => 'NE',
            'alpha3'     => 'NER',
            'numeric'    => '562',
            'tld'        => '.ne',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'NG' => [
            'alpha2'     => 'NG',
            'alpha3'     => 'NGA',
            'numeric'    => '566',
            'tld'        => '.ng',
            'currencies' => ['NGN',],
            'continents'  => ['AF'],
        ],
        'NU' => [
            'alpha2'     => 'NU',
            'alpha3'     => 'NIU',
            'numeric'    => '570',
            'tld'        => '.nu',
            'currencies' => ['NZD',],
            'continents'  => ['OC'],
        ],
        'NF' => [
            'alpha2'     => 'NF',
            'alpha3'     => 'NFK',
            'numeric'    => '574',
            'tld'        => '.nf',
            'currencies' => ['AUD',],
            'continents'  => ['OC'],
        ],
        'MP' => [
            'alpha2'     => 'MP',
            'alpha3'     => 'MNP',
            'numeric'    => '580',
            'tld'        => '.mp',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'NO' => [
            'alpha2'     => 'NO',
            'alpha3'     => 'NOR',
            'numeric'    => '578',
            'tld'        => '.no',
            'currencies' => ['NOK',],
            'languages'  => ['NO', 'SE'],
            'continents'  => ['EU'],
        ],
        'OM' => [
            'alpha2'     => 'OM',
            'alpha3'     => 'OMN',
            'numeric'    => '512',
            'tld'        => '.om',
            'currencies' => ['OMR',],
            'continents'  => ['AS'],
        ],
        'PK' => [
            'alpha2'     => 'PK',
            'alpha3'     => 'PAK',
            'numeric'    => '586',
            'tld'        => '.pk',
            'currencies' => ['PKR',],
            'continents'  => ['AS'],
        ],
        'PW' => [
            'alpha2'     => 'PW',
            'alpha3'     => 'PLW',
            'numeric'    => '585',
            'tld'        => '.pw',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'PS' => [
            'alpha2'     => 'PS',
            'alpha3'     => 'PSE',
            'numeric'    => '275',
            'tld'        => '.ps',
            'currencies' => ['ILS',],
            'continents'  => ['AS'],
        ],
        'PA' => [
            'alpha2'     => 'PA',
            'alpha3'     => 'PAN',
            'numeric'    => '591',
            'tld'        => '.pa',
            'currencies' => ['PAB',],
            'languages'  => ['ES'],
            'continents'  => ['NA'],
        ],
        'PG' => [
            'alpha2'     => 'PG',
            'alpha3'     => 'PNG',
            'numeric'    => '598',
            'tld'        => '.pg',
            'currencies' => ['PGK',],
            'continents'  => ['OC'],
        ],
        'PY' => [
            'alpha2'     => 'PY',
            'alpha3'     => 'PRY',
            'numeric'    => '600',
            'tld'        => '.py',
            'currencies' => ['PYG',],
            'languages'  => ['ES', 'GN'],
            'continents'  => ['SA'],
        ],
        'PE' => [
            'alpha2'     => 'PE',
            'alpha3'     => 'PER',
            'numeric'    => '604',
            'tld'        => '.pe',
            'currencies' => ['PEN',],
            'languages'  => ['ES', 'AY', 'QU'],
            'continents'  => ['SA'],
        ],
        'PH' => [
            'alpha2'     => 'PH',
            'alpha3'     => 'PHL',
            'numeric'    => '608',
            'tld'        => '.ph',
            'currencies' => ['PHP',],
            'continents'  => ['AS'],
        ],
        'PN' => [
            'alpha2'     => 'PN',
            'alpha3'     => 'PCN',
            'numeric'    => '612',
            'tld'        => '.pn',
            'currencies' => ['NZD',],
            'continents'  => ['OC'],
        ],
        'PL' => [
            'alpha2'     => 'PL',
            'alpha3'     => 'POL',
            'numeric'    => '616',
            'tld'        => '.pl',
            'currencies' => ['PLN',],
            'languages'  => ['PL'],
            'continents'  => ['EU'],
        ],
        'PT' => [
            'alpha2'     => 'PT',
            'alpha3'     => 'PRT',
            'numeric'    => '620',
            'tld'        => '.pt',
            'currencies' => ['EUR',],
            'languages'  => ['PT'],
            'continents'  => ['EU'],
        ],
        'PR' => [
            'alpha2'     => 'PR',
            'alpha3'     => 'PRI',
            'numeric'    => '630',
            'tld'        => '.pr',
            'currencies' => ['USD',],
            'continents'  => ['NA'],
        ],
        'QA' => [
            'alpha2'     => 'QA',
            'alpha3'     => 'QAT',
            'numeric'    => '634',
            'tld'        => '.qa',
            'currencies' => ['QAR',],
            'continents'  => ['AS'],
        ],
        'RE' => [
            'alpha2'     => 'RE',
            'alpha3'     => 'REU',
            'numeric'    => '638',
            'tld'        => '.re',
            'currencies' => ['EUR',],
            'continents'  => ['AF'],
        ],
        'RO' => [
            'alpha2'     => 'RO',
            'alpha3'     => 'ROU',
            'numeric'    => '642',
            'tld'        => '.ro',
            'currencies' => ['RON',],
            'languages'  => ['RO'],
            'continents'  => ['EU'],
        ],
        'RU' => [
            'alpha2'     => 'RU',
            'alpha3'     => 'RUS',
            'numeric'    => '643',
            'tld'        => '.ru',
            'currencies' => ['RUB',],
            'continents'  => ['EU', 'AS'],
        ],
        'RW' => [
            'alpha2'     => 'RW',
            'alpha3'     => 'RWA',
            'numeric'    => '646',
            'tld'        => '.rw',
            'currencies' => ['RWF',],
            'continents'  => ['AF'],
        ],
        'BL' => [
            'alpha2'     => 'BL',
            'alpha3'     => 'BLM',
            'numeric'    => '652',
            'tld'        => '.bl',
            'currencies' => ['EUR',],
            'continents'  => ['NA'],
        ],
        'SH' => [
            'alpha2'     => 'SH',
            'alpha3'     => 'SHN',
            'numeric'    => '654',
            'tld'        => '.sh',
            'currencies' => ['SHP',],
            'continents'  => ['AF'],
        ],
        'KN' => [
            'alpha2'     => 'KN',
            'alpha3'     => 'KNA',
            'numeric'    => '659',
            'tld'        => '.kn',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'LC' => [
            'alpha2'     => 'LC',
            'alpha3'     => 'LCA',
            'numeric'    => '662',
            'tld'        => '.lc',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'MF' => [
            'alpha2'     => 'MF',
            'alpha3'     => 'MAF',
            'numeric'    => '663',
            'tld'        => '.mf',
            'currencies' => ['EUR', 'USD',],
            'continents'  => ['NA'],
        ],
        'PM' => [
            'alpha2'     => 'PM',
            'alpha3'     => 'SPM',
            'numeric'    => '666',
            'tld'        => '.pm',
            'currencies' => ['EUR',],
            'continents'  => ['NA'],
        ],
        'VC' => [
            'alpha2'     => 'VC',
            'alpha3'     => 'VCT',
            'numeric'    => '670',
            'tld'        => '.vc',
            'currencies' => ['XCD',],
            'continents'  => ['NA'],
        ],
        'WS' => [
            'alpha2'     => 'WS',
            'alpha3'     => 'WSM',
            'numeric'    => '882',
            'tld'        => '.ws',
            'currencies' => ['WST',],
            'continents'  => ['OC'],
        ],
        'SM' => [
            'alpha2'     => 'SM',
            'alpha3'     => 'SMR',
            'numeric'    => '674',
            'tld'        => '.sm',
            'currencies' => ['EUR',],
            'continents'  => ['EU'],
        ],
        'ST' => [
            'alpha2'     => 'ST',
            'alpha3'     => 'STP',
            'numeric'    => '678',
            'tld'        => '.st',
            'currencies' => ['STN',],
            'continents'  => ['AF'],
        ],
        'SA' => [
            'alpha2'     => 'SA',
            'alpha3'     => 'SAU',
            'numeric'    => '682',
            'tld'        => '.sa',
            'currencies' => ['SAR',],
            'continents'  => ['AS'],
        ],
        'SN' => [
            'alpha2'     => 'SN',
            'alpha3'     => 'SEN',
            'numeric'    => '686',
            'tld'        => '.sn',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'RS' => [
            'alpha2'     => 'RS',
            'alpha3'     => 'SRB',
            'numeric'    => '688',
            'tld'        => '.rs',
            'currencies' => ['RSD',],
            'languages'  => ['SR'],
            'continents'  => ['EU'],
        ],
        'SC' => [
            'alpha2'     => 'SC',
            'alpha3'     => 'SYC',
            'numeric'    => '690',
            'tld'        => '.sc',
            'currencies' => ['SCR',],
            'continents'  => ['AF'],
        ],
        'SL' => [
            'alpha2'     => 'SL',
            'alpha3'     => 'SLE',
            'numeric'    => '694',
            'tld'        => '.sl',
            'currencies' => ['SLL',],
            'continents'  => ['AF'],
        ],
        'SG' => [
            'alpha2'     => 'SG',
            'alpha3'     => 'SGP',
            'numeric'    => '702',
            'tld'        => '.sg',
            'currencies' => ['SGD',],
            'continents'  => ['AS'],
        ],
        'SX' => [
            'alpha2'     => 'SX',
            'alpha3'     => 'SXM',
            'numeric'    => '534',
            'tld'        => '.sx',
            'currencies' => ['ANG',],
            'continents'  => ['NA'],
        ],
        'SK' => [
            'alpha2'     => 'SK',
            'alpha3'     => 'SVK',
            'numeric'    => '703',
            'tld'        => '.sk',
            'currencies' => ['EUR',],
            'languages'  => ['SK'],
            'continents'  => ['EU'],
        ],
        'SI' => [
            'alpha2'     => 'SI',
            'alpha3'     => 'SVN',
            'numeric'    => '705',
            'tld'        => '.si',
            'currencies' => ['EUR',],
            'languages'  => ['SL'],
            'continents'  => ['EU'],
        ],
        'SB' => [
            'alpha2'     => 'SB',
            'alpha3'     => 'SLB',
            'numeric'    => '090',
            'tld'        => '.sb',
            'currencies' => ['SBD',],
            'continents'  => ['OC'],
        ],
        'SO' => [
            'alpha2'     => 'SO',
            'alpha3'     => 'SOM',
            'numeric'    => '706',
            'tld'        => '.so',
            'currencies' => ['SOS',],
            'continents'  => ['AF'],
        ],
        'ZA' => [
            'alpha2'     => 'ZA',
            'alpha3'     => 'ZAF',
            'numeric'    => '710',
            'tld'        => '.za',
            'currencies' => ['ZAR',],
            'continents'  => ['AF'],
        ],
        'GS' => [
            'alpha2'     => 'GS',
            'alpha3'     => 'SGS',
            'numeric'    => '239',
            'tld'        => '.gs',
            'currencies' => ['GBP',],
            'continents'  => ['AN'],
        ],
        'SS' => [
            'alpha2'     => 'SS',
            'alpha3'     => 'SSD',
            'numeric'    => '728',
            'tld'        => '.ss',
            'currencies' => ['SSP',],
            'continents'  => ['AF'],
        ],
        'ES' => [
            'alpha2'     => 'ES',
            'alpha3'     => 'ESP',
            'numeric'    => '724',
            'tld'        => '.es',
            'currencies' => ['EUR',],
            'languages'  => ['ES'],
            'continents'  => ['EU'],
        ],
        'LK' => [
            'alpha2'     => 'LK',
            'alpha3'     => 'LKA',
            'numeric'    => '144',
            'tld'        => '.lk',
            'currencies' => ['LKR',],
            'continents'  => ['AS'],
        ],
        'SD' => [
            'alpha2'     => 'SD',
            'alpha3'     => 'SDN',
            'numeric'    => '729',
            'tld'        => '.sd',
            'currencies' => ['SDG',],
            'continents'  => ['AF'],
        ],
        'SR' => [
            'alpha2'     => 'SR',
            'alpha3'     => 'SUR',
            'numeric'    => '740',
            'tld'        => '.sr',
            'currencies' => ['SRD',],
            'continents'  => ['SA'],
        ],
        'SJ' => [
            'alpha2'     => 'SJ',
            'alpha3'     => 'SJM',
            'numeric'    => '744',
            'tld'        => '.sj',
            'currencies' => ['NOK',],
            'continents'  => ['EU'],
        ],
        'SE' => [
            'alpha2'     => 'SE',
            'alpha3'     => 'SWE',
            'numeric'    => '752',
            'tld'        => '.se',
            'currencies' => ['SEK',],
            'languages'  => ['SV'],
            'continents'  => ['EU'],
        ],
        'CH' => [
            'alpha2'     => 'CH',
            'alpha3'     => 'CHE',
            'numeric'    => '756',
            'tld'        => '.ch',
            'currencies' => ['CHF',],
            'languages'  => ['FR', 'DE', 'IT', 'RM'],
            'continents'  => ['EU'],
        ],
        'SY' => [
            'alpha2'     => 'SY',
            'alpha3'     => 'SYR',
            'numeric'    => '760',
            'tld'        => '.sy',
            'currencies' => ['SYP',],
            'continents'  => ['AS'],
        ],
        'TW' => [
            'alpha2'     => 'TW',
            'alpha3'     => 'TWN',
            'numeric'    => '158',
            'tld'        => '.tw',
            'currencies' => ['TWD',],
            'continents'  => ['AS'],
        ],
        'TJ' => [
            'alpha2'     => 'TJ',
            'alpha3'     => 'TJK',
            'numeric'    => '762',
            'tld'        => '.tj',
            'currencies' => ['TJS',],
            'continents'  => ['AS'],
        ],
        'TZ' => [
            'alpha2'     => 'TZ',
            'alpha3'     => 'TZA',
            'numeric'    => '834',
            'tld'        => '.tz',
            'currencies' => ['TZS',],
            'continents'  => ['AF'],
        ],
        'TH' => [
            'alpha2'     => 'TH',
            'alpha3'     => 'THA',
            'numeric'    => '764',
            'tld'        => '.th',
            'currencies' => ['THB',],
            'continents'  => ['AS'],
        ],
        'TL' => [
            'alpha2'     => 'TL',
            'alpha3'     => 'TLS',
            'numeric'    => '626',
            'tld'        => '.tl',
            'currencies' => ['USD',],
            'continents'  => ['AS'],
        ],
        'TG' => [
            'alpha2'     => 'TG',
            'alpha3'     => 'TGO',
            'numeric'    => '768',
            'tld'        => '.tg',
            'currencies' => ['XOF',],
            'continents'  => ['AF'],
        ],
        'TK' => [
            'alpha2'     => 'TK',
            'alpha3'     => 'TKL',
            'numeric'    => '772',
            'tld'        => '.tk',
            'currencies' => ['NZD',],
            'continents'  => ['OC'],
        ],
        'TO' => [
            'alpha2'     => 'TO',
            'alpha3'     => 'TON',
            'numeric'    => '776',
            'tld'        => '.to',
            'currencies' => ['TOP',],
            'continents'  => ['OC'],
        ],
        'TT' => [
            'alpha2'     => 'TT',
            'alpha3'     => 'TTO',
            'numeric'    => '780',
            'tld'        => '.tt',
            'currencies' => ['TTD',],
            'continents'  => ['NA'],
        ],
        'TN' => [
            'alpha2'     => 'TN',
            'alpha3'     => 'TUN',
            'numeric'    => '788',
            'tld'        => '.tn',
            'currencies' => ['TND',],
            'continents'  => ['AF'],
        ],
        'TR' => [
            'alpha2'     => 'TR',
            'alpha3'     => 'TUR',
            'numeric'    => '792',
            'tld'        => '.tr',
            'currencies' => ['TRY',],
            'continents'  => ['AS'],
        ],
        'TM' => [
            'alpha2'     => 'TM',
            'alpha3'     => 'TKM',
            'numeric'    => '795',
            'tld'        => '.tm',
            'currencies' => ['TMT',],
            'continents'  => ['AS'],
        ],
        'TC' => [
            'alpha2'     => 'TC',
            'alpha3'     => 'TCA',
            'numeric'    => '796',
            'tld'        => '.tc',
            'currencies' => ['USD',],
            'continents'  => ['NA'],
        ],
        'TV' => [
            'alpha2'     => 'TV',
            'alpha3'     => 'TUV',
            'numeric'    => '798',
            'tld'        => '.tv',
            'currencies' => ['AUD',],
            'continents'  => ['OC'],
        ],
        'UG' => [
            'alpha2'     => 'UG',
            'alpha3'     => 'UGA',
            'numeric'    => '800',
            'tld'        => '.ug',
            'currencies' => ['UGX',],
            'continents'  => ['AF'],
        ],
        'UA' => [
            'alpha2'     => 'UA',
            'alpha3'     => 'UKR',
            'numeric'    => '804',
            'tld'        => '.ua',
            'currencies' => ['UAH',],
            'languages'  => ['UK', 'RU'],
            'continents'  => ['EU'],
        ],
        'AE' => [
            'alpha2'     => 'AE',
            'alpha3'     => 'ARE',
            'numeric'    => '784',
            'tld'        => '.ae',
            'currencies' => ['AED',],
            'continents'  => ['AS'],
        ],
        'GB' => [
            'alpha2'     => 'GB',
            'alpha3'     => 'GBR',
            'numeric'    => '826',
            'tld'        => '.uk',
            'currencies' => ['GBP',],
            'languages'  => ['EN', 'KW', 'GA', 'GD', 'CY', 'GV'],
            'continents'  => ['EU'],
        ],
        'US' => [
            'alpha2'     => 'US',
            'alpha3'     => 'USA',
            'numeric'    => '840',
            'tld'        => '.us',
            'currencies' => ['USD',],
            'languages'  => ['EN'],
            'continents'  => ['NA'],
        ],
        'UM' => [
            'alpha2'     => 'UM',
            'alpha3'     => 'UMI',
            'numeric'    => '581',
            'tld'        => '.um',
            'currencies' => ['USD',],
            'continents'  => ['OC'],
        ],
        'UY' => [
            'alpha2'     => 'UY',
            'alpha3'     => 'URY',
            'numeric'    => '858',
            'tld'        => '.uy',
            'currencies' => ['UYU',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'UZ' => [
            'alpha2'     => 'UZ',
            'alpha3'     => 'UZB',
            'numeric'    => '860',
            'tld'        => '.uz',
            'currencies' => ['UZS',],
            'continents'  => ['AS'],
        ],
        'VU' => [
            'alpha2'     => 'VU',
            'alpha3'     => 'VUT',
            'numeric'    => '548',
            'tld'        => '.vu',
            'currencies' => ['VUV',],
            'continents'  => ['OC'],
        ],
        'VE' => [
            'alpha2'     => 'VE',
            'alpha3'     => 'VEN',
            'numeric'    => '862',
            'tld'        => '.ve',
            'currencies' => ['VEF',],
            'languages'  => ['ES'],
            'continents'  => ['SA'],
        ],
        'VN' => [
            'alpha2'     => 'VN',
            'alpha3'     => 'VNM',
            'numeric'    => '704',
            'tld'        => '.vn',
            'currencies' => ['VND',],
            'continents'  => ['AS'],
        ],
        'VG' => [
            'alpha2'     => 'VG',
            'alpha3'     => 'VGB',
            'numeric'    => '092',
            'tld'        => '.vg',
            'currencies' => ['USD',],
            'continents'  => ['NA'],
        ],
        'VI' => [
            'alpha2'     => 'VI',
            'alpha3'     => 'VIR',
            'numeric'    => '850',
            'tld'        => '.vi',
            'currencies' => ['USD',],
            'continents'  => ['NA'],
        ],
        'WF' => [
            'alpha2'     => 'WF',
            'alpha3'     => 'WLF',
            'numeric'    => '876',
            'tld'        => '.wf',
            'currencies' => ['XPF',],
            'continents'  => ['OC'],
        ],
        'EH' => [
            'alpha2'     => 'EH',
            'alpha3'     => 'ESH',
            'numeric'    => '732',
            'tld'        => '.eh',
            'currencies' => ['MAD',],
            'continents'  => ['AF'],
        ],
        'YE' => [
            'alpha2'     => 'YE',
            'alpha3'     => 'YEM',
            'numeric'    => '887',
            'tld'        => '.ye',
            'currencies' => ['YER',],
            'continents'  => ['AS'],
        ],
        'ZM' => [
            'alpha2'     => 'ZM',
            'alpha3'     => 'ZMB',
            'numeric'    => '894',
            'tld'        => '.zm',
            'currencies' => ['ZMW',],
            'continents'  => ['AF'],
        ],
        'ZW' => [
            'alpha2'     => 'ZW',
            'alpha3'     => 'ZWE',
            'numeric'    => '716',
            'tld'        => '.zw',
            'currencies' => ['BWP', 'EUR', 'GBP', 'USD', 'ZAR',],
            'continents'  => ['AF'],
        ],
    ];


}